### ISSUE TITLE
Move template.hbs alongside route.js or component.js

### ISSUE THREAD

**Issue by apellerano-pw** [ijlee2/ember-codemod-pod-to-octane#68]
Ember's component blueprint will nest components under the `app/components/` directory. However it's also valid Ember to place components directly in a pod folder under the `app/` root.

Both of these are valid components
```
app/
  components/
    my-pod-b/
      component.js
      template.hbs
  my-pod-a/
    component.js
    template.hbs
```

Problem is route templates pod similarly to `my-pod-a`, and if all you're looking at is template.hbs you have no way to know if it's a route or a component template. You need the broader context of there being a route.js or component.js present.

If you have components stored like `my-pod-a` and run this codemod, the map-route-template will move the component's template.hbs into the `app/templates/` folder, and map-component-classes will never move the component.js. This breaks the component.

I don't see a way to fix this with the current architecture. I think there needs to be a more broad map-route and map-component concept which, upon spotting a route.js or component.js, also look for the sibling template.hbs and move it appropriately.

**Comment by apellerano-pw** [comment]
One more complication is that a lone template.hbs as in

```
app/
  my-pod-c/
    template.hbs
```

is a route template, but the absence of sibling component.js is the only way to know that.

**Comment by ijlee2** [comment]
I didn't know that a component class could live outside the `components` folder, and appreciate your documenting an edge case (maybe it's an unintended bug in `ember-cli` or `ember-source`?).

In general, the codemods that I write target the 80% case, and I leave it up to end-developers to handle the other 20% (e.g. things specific to their project). Since the command `ember g component` creates component classes in `components` for podded projects and Ember CLI documents so in [cli.emberjs.com](https://cli.emberjs.com/release/advanced-use/project-layouts/#podslayout), I think it's okay for the codemod to not handle this edge case.

```
# Copied from cli.emberjs.com
app
├── components
|   └── tags
|       ├── component.js
|       └── template.hbs
├── post      
|   ├── controller.js
|   ├── model.js
|   ├── route.js
|   └── template.hbs
├── app.js
├── index.html
├── resolver.js
└── router.js
```

**Comment by ijlee2** [comment]
I'll close the issue, as I think the described case is an edge case and don't currently have time to look into possible solutions. (Will reopen it later if needed.)

**Comment by gorner** [comment]
> I didn't know that a component class could live outside the `components` folder

As a developer on an app with a lot of route-specific components using the structure `app/pods/<route-path>/<component-name>/{component.js,template.hbs}` (and relatively few under `app/pods/components`) I'm a bit surprised this is considered an edge case and thus this codemod doesn't work for most of our components. But I also can't see anywhere that component structure was ever suggested or recommended.

I suppose these sorts of edge cases are what AI agents are for now 🙃

**Comment by ijlee2** [comment]
Hi, @gorner. It has been a while since I've looked at a pod project. I wonder, in your case with `app/pods`, if adding the [`--pod-path` option](https://github.com/ijlee2/ember-codemod-pod-to-octane/tree/5.0.4#arguments) might help.

```sh
pnpx ember-codemod-pod-to-octane --pod-path pods
```

To clarify, were you saying that the codemod hadn't worked with this option?

**Comment by gorner** [comment]
@ijlee2 It didn't error but it left a lot of components under the sorts of paths I mentioned (`app/pods/<route-path>/<component-name>/`) untouched. Components under `app/pods/components` were moved successfully.

**Comment by ijlee2** [comment]
Thanks for the additional info. I'll see if I can generalize the file paths for search in the next few days.

To clarify, what I might be able to solve at the moment is the following:

- If a folder outside of `/components` has the file `component.{js,ts}`, then move the folder to `app/components`.

That is, determining whether a folder with just `template.hbs` belongs to `app/components` or `app/templates` will be out of scope.

**Comment by ijlee2** [comment]
@gorner Version `5.1.0` handles component files outside of `/components` (apps only). Can you help test it please?

**Comment by gorner** [comment]
@ijlee2 Thanks, with the `--type=app --pod-path=pods` options it does most of what we would need for the app-side code. That said we have a lot of template-only components under `app/pods` (which as you've noted above are moved to `app/templates` by default) so we would have to rectify that manually, I realize it would be a challenge to try to parse the router map to distinguish.

On the testing side we have some component integration test files with the format `tests/integration/pods/<path>/component-test.js`. Test files under `pods/components` are moved successfully, but those under other `pods/*` folders are left untouched. If you want to revisit, great, but we could probably just move all the other folders under `components` before trying the codemod again.

**Comment by ijlee2** [comment]
@gorner Cool, I'm glad to hear that there is more progress. I have to work on other things in the next few weeks, so I recommend that you go ahead with moving the remaining files manually.

What I also recommend is an incremental migration: If my guess is right, the rendering tests can stay where they are. These tests will continue to pass, if and only if, the corresponding components are moved to the flat or nested layout correctly. You can use application tests to check whether you moved the route templates correctly.

After you finish un-podding the source files, you can then move the (remaining) rendering tests to `tests/integration/{components,helpers,modifiers}`, and the remaining unit tests similarly.
